export const RECEIVE_AUTOCOMPLETE_RESPONSE = 'RECEIVE_AUTOCOMPLETE_RESPONSE';
export const RECEIVE_AUTOCOMPLETE_ERROR = 'RECEIVE_AUTOCOMPLETE_ERROR';
export const CHANGE_INPUT = 'CHANGE_INPUT';
export const CHANGE_SEARCH_TERM = 'CHANGE_SEARCH_TERM';
